// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnWiyWvaINJifdsiAawLROXZCO1oxaad0',
    appId: '1:832646305206:web:b0d3bf47b53db424501d17',
    messagingSenderId: '832646305206',
    projectId: 'mathstars-e6be2',
    authDomain: 'mathstars-e6be2.firebaseapp.com',
    storageBucket: 'mathstars-e6be2.firebasestorage.app',
    measurementId: 'G-5ZWYZTZZFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlVawoWCqgi_VFK74KIFCFa1nTe8yBiWE',
    appId: '1:832646305206:android:0426028dae3c7b18501d17',
    messagingSenderId: '832646305206',
    projectId: 'mathstars-e6be2',
    storageBucket: 'mathstars-e6be2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLADERbukwhzcy52TWwo6FWPXuaN2TaU8',
    appId: '1:832646305206:ios:b63f1b06a4ffc815501d17',
    messagingSenderId: '832646305206',
    projectId: 'mathstars-e6be2',
    storageBucket: 'mathstars-e6be2.firebasestorage.app',
    iosBundleId: 'com.example.pleaseWorkTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLADERbukwhzcy52TWwo6FWPXuaN2TaU8',
    appId: '1:832646305206:ios:b63f1b06a4ffc815501d17',
    messagingSenderId: '832646305206',
    projectId: 'mathstars-e6be2',
    storageBucket: 'mathstars-e6be2.firebasestorage.app',
    iosBundleId: 'com.example.pleaseWorkTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnWiyWvaINJifdsiAawLROXZCO1oxaad0',
    appId: '1:832646305206:web:e6d4f5f862297589501d17',
    messagingSenderId: '832646305206',
    projectId: 'mathstars-e6be2',
    authDomain: 'mathstars-e6be2.firebaseapp.com',
    storageBucket: 'mathstars-e6be2.firebasestorage.app',
    measurementId: 'G-ZHSXQZ72Y0',
  );

}